Readerself\CoreBundle\Entity\ActionCategory:
    repositoryClass: Readerself\CoreBundle\Repository\ActionCategoryRepository
    type: entity
    table: action_category
    indexes:
        category_id:
            columns:
                - category_id
        action_id:
            columns:
                - action_id
        member_id:
            columns:
                - member_id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: true
            id: true
            generator:
                strategy: IDENTITY
    fields:
        dateCreated:
            type: datetime
            nullable: false
            column: date_created
    manyToOne:
        category:
            targetEntity: Category
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                category_id:
                    nullable: false
                    referencedColumnName: id
                    onDelete: "cascade"
            orphanRemoval: false
        action:
            targetEntity: Action
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                action_id:
                    nullable: false
                    referencedColumnName: id
                    onDelete: "cascade"
            orphanRemoval: false
        member:
            targetEntity: Member
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                member_id:
                    nullable: true
                    referencedColumnName: id
                    onDelete: "cascade"
            orphanRemoval: false

    lifecycleCallbacks: {  }
